= {project-name}
Marat Radchenko <marat@slonopotamus.org>
:project-name: Asciidoctor FB2
:project-handle: asciidoctor-fb2
:slug: slonopotamus/{project-handle}
:uri-project: https://github.com/{slug}
:uri-ci: {uri-project}/actions?query=branch%3Amaster
:uri-gem: https://rubygems.org/gems/{project-handle}

image:https://img.shields.io/gem/v/{project-handle}.svg[Latest Release,link={uri-gem}]
image:{uri-project}/workflows/CI/badge.svg?branch=master[Build Status,link={uri-ci}]

{project-name} is an Asciidoctor extension for converting AsciiDoc documents directly to the FB2 e-book format.

== Installation

[source,shell script]
----
$ gem install asciidoctor-fb2 --pre
----

== Usage

[source,shell script]
----
asciidoctor-fb2 /path/to/book.adoc
----

== Development

After checking out the repo, run `bundle install` to install dependencies.
Then, run `bundle exec rake spec` to run the tests.

=== FB2-related AsciiDoc Attributes

The metadata in the generated FB2 file is populated from attributes in the AsciiDoc document.
The names of the attributes and the metadata elements to which they map are documented in this section.

.AsciiDoc attributes that control the FB2 metadata
[cols="1m,3"]
|===
|Name |Description

|uuid
|Populates unique book identifier in FB2 metadata.

|lang
|Populates the content language in FB2 metadata.

|keywords
|Populates keywords list in FB2 metadata
The keywords should be represented as comma-separated values (CSV).

|genres
|Populates genres list in FB2 metadata
The genres should be represented as comma-separated values (CSV).
|===
